DROP TABLE IF EXISTS games;
CREATE TABLE games(id INTEGER IDENTITY,
game VARCHAR(50));

DROP TABLE IF EXISTS users;
CREATE TABLE users(id INTEGER IDENTITY,
username VARCHAR(50));

DROP TABLE IF EXISTS scores;
CREATE TABLE scores(id INTEGER IDENTITY,
game_id INTEGER,
user_id INTEGER,
score INTEGER);
